name: build-ndk

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install unzip and wget
      run: sudo apt-get install -y unzip wget

    - name: Download Android NDK r21e
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -O ndk.zip
        unzip ndk.zip -d $HOME
        mv $HOME/android-ndk-r21e $HOME/ndk

    - name: Set ANDROID_NDK_HOME
      run: echo "ANDROID_NDK_HOME=$HOME/ndk" >> $GITHUB_ENV

    - name: Run ndk-build
      run: |
        export ANDROID_NDK_HOME=$HOME/ndk
        cd jni
        $ANDROID_NDK_HOME/ndk-build
        mkdir -p $GITHUB_WORKSPACE/out
        cp -r ../libs $GITHUB_WORKSPACE/out

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: serial-port-libs
        path: out/
